version: '3.8'

services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PGUSER=myuser
      - PGHOST=postgres
      - PGDATABASE=mydb
      - PGPASSWORD=mypassword
      - PGPORT=5432
    networks:
      - frontend-net
      - backend-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - frontend-net

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
      - client
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

volumes:
  pgdata: